<img src="https://cursos.virtual.uniandes.edu.co/isis4219/wp-content/uploads/sites/162/2014/11/cropped-misisheader.png" ><br>
<h1> Detector de uso correcto de tapabocas con Machine learning </h1>
<h1> Obtención, perfilamiento y preparación de los datos </h1>
    
Julián Montoya - 201615817

<h1>Contenido<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1-Imports-necesarios" data-toc-modified-id="1-Imports-necesarios-1">1 Imports necesarios</a></span></li><li><span><a href="#2.-Obtención-de-datos" data-toc-modified-id="2.-Obtención-de-datos-2">2. Obtención de datos</a></span></li><li><span><a href="#3.-Perfilamiento-de-datos-originales" data-toc-modified-id="3.-Perfilamiento-de-datos-originales-3">3. Perfilamiento de datos originales</a></span><ul class="toc-item"><li><span><a href="#3.1-Perfilamiento-fuentes-de-datos-#1" data-toc-modified-id="3.1-Perfilamiento-fuentes-de-datos-#1-3.1">3.1 Perfilamiento fuentes de datos #1</a></span><ul class="toc-item"><li><span><a href="#Insights-sobre-data-set-#1" data-toc-modified-id="Insights-sobre-data-set-#1-3.1.1">Insights sobre data set #1</a></span></li></ul></li><li><span><a href="#3.2-Perfilamiento-fuentes-de-datos-#2" data-toc-modified-id="3.2-Perfilamiento-fuentes-de-datos-#2-3.2">3.2 Perfilamiento fuentes de datos #2</a></span><ul class="toc-item"><li><span><a href="#Insights-sobre-data-set-#2" data-toc-modified-id="Insights-sobre-data-set-#2-3.2.1">Insights sobre data set #2</a></span></li></ul></li><li><span><a href="#3.3-Perfilamiento-fuente-de-datos-#3" data-toc-modified-id="3.3-Perfilamiento-fuente-de-datos-#3-3.3">3.3 Perfilamiento fuente de datos #3</a></span><ul class="toc-item"><li><span><a href="#Insights-fuente-de-datos-#3" data-toc-modified-id="Insights-fuente-de-datos-#3-3.3.1">Insights fuente de datos #3</a></span></li></ul></li><li><span><a href="#3.4-Perfilamiento-fuente-de-datos-#4" data-toc-modified-id="3.4-Perfilamiento-fuente-de-datos-#4-3.4">3.4 Perfilamiento fuente de datos #4</a></span><ul class="toc-item"><li><span><a href="#Insights-sobre-data-set-#4" data-toc-modified-id="Insights-sobre-data-set-#4-3.4.1">Insights sobre data set #4</a></span></li></ul></li></ul></li><li><span><a href="#4-Limpieza-de-datos:" data-toc-modified-id="4-Limpieza-de-datos:-4">4 Limpieza de datos:</a></span></li><li><span><a href="#5.-Procesamiento" data-toc-modified-id="5.-Procesamiento-5">5. Procesamiento</a></span><ul class="toc-item"><li><span><a href="#2.1-Simulación-de-tapabocas-con-face-recognition-(Con-fuentes-de-datos-1-y-2)" data-toc-modified-id="2.1-Simulación-de-tapabocas-con-face-recognition-(Con-fuentes-de-datos-1-y-2)-5.1">2.1 Simulación de tapabocas con face recognition (Con fuentes de datos 1 y 2)</a></span></li><li><span><a href="#2.2-Resultados-de-la-simulación" data-toc-modified-id="2.2-Resultados-de-la-simulación-5.2">2.2 Resultados de la simulación</a></span></li><li><span><a href="#2.3-Limpieza-manual-sobre-los-resultados-de-la-simulación" data-toc-modified-id="2.3-Limpieza-manual-sobre-los-resultados-de-la-simulación-5.3">2.3 Limpieza manual sobre los resultados de la simulación</a></span></li><li><span><a href="#2.4-Separar-caras-según-label-en-fuente-de-datos-3-(Añadido-revisión-1)" data-toc-modified-id="2.4-Separar-caras-según-label-en-fuente-de-datos-3-(Añadido-revisión-1)-5.4">2.4 Separar caras según label en fuente de datos 3 (Añadido revisión 1)</a></span></li><li><span><a href="#2.4-Separar-train-y-test" data-toc-modified-id="2.4-Separar-train-y-test-5.5">2.4 Separar train y test</a></span></li></ul></li></ul></div>

## 1 Imports necesarios

In [7]:
#Pandas
from pandas_profiling import ProfileReport
import pandas as pd

#Numpy
import numpy as np

#PIL
from PIL import Image

# files
import sys
import os
from shutil import copyfile

#Cufflink and plotly
import cufflinks as cf
import plotly.offline
cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)

# sklearn
from sklearn.model_selection import train_test_split

# Read XML
import xml.etree.ElementTree as ET

## 2. Obtención de datos

Para crear el modelo se obtienen imagenes de caras de personas las siguiente fuentes:


1.  Real world masked face dataset en github: https://github.com/X-zhangyang/Real-World-Masked-Face-Dataset
2.  Data set de caras in kaggle : https://www.kaggle.com/jessicali9530/lfw-dataset
3.  Data set de deteccion de uso correcto de tapabocas de Andrewmvd en kaggle: https://www.kaggle.com/andrewmvd/face-mask-detection
4.  Data set de deteccion de uso de tapabocas de Wobot Intelligence en kaggle: https://www.kaggle.com/wobotintelligence/face-mask-detection-dataset
5.  Data set de deteccion de uso de tapabocas de Ashish Jangra en kaggle: https://www.kaggle.com/ashishjangra27/face-mask-12k-images-dataset

Todas se descargaron y se subieron al repositorio del proyecto

In [61]:
# Directories of the downloaded original data

dir1 = 'OriginalDjta/lfw-deepfunneled/'

dir2 = 'OriginalData/self-built-masked-face-recognition-dataset/'

dir3_annotations = 'OriginalData/kaggle_andrewmvd/annotations/'
dir3_images = 'OriginalData/kaggle_andrewmvd/images/'

dir4 = 'OriginalData/Ashish Jangra Face Mask Dataset'

## 3. Perfilamiento de datos originales

Se obtiene de cada imagen la altura, el ancho, el directorio, el tamaño en bytes, el formato, y el sujeto de la imagen (si aplica).

### 3.1 Perfilamiento fuentes de datos #1

La primera fuente de datos contiene únicamente fotos de personas que no están usando tapaboca. La estructura de la data set consiste en una lista de carpetas por sujeto, donde dentro hay 1 o más fotos de la cara de la persona.

In [14]:
# Función que permite leer la data set descrita anteriormente dadas las columnas para guardar la información relevante
# y el directorio donde se encuentra
def readDataSetWithSubjects(directory, widthColumn, heightColumn, dirColumn, sizeMemoryColumn, subjectColumn, formatColumn):
    
    # Iterate over the directories in the data set
    files = os.listdir(directory)
    for f in files:
        
        # Directory from each person
        dirPerson = directory + f

        #Iterate over the images of each person
        for i in os.listdir(dirPerson):
            #Dir of an image of the person
            dirImg = dirPerson + '/' + i
        
            #Get width, height, size
            img = Image.open(dirImg)
            width, height = img.size
            size = os.stat(dirImg).st_size
            
            # Get the format
            formatOfImg = dirImg.split(".")[-1]
        
            #Append the data to the arrays
            widthColumn.append(width)
            heightColumn.append(height)
            sizeMemoryColumn.append(size)
            dirColumn.append(dirImg)
            subjectColumn.append(f)
            formatColumn.append(formatOfImg)
            
 

In [15]:
# We obtain width, height, directory, size in bytes and subject
widthCol_DS1 = []
heightCol_DS1 = []
dirCol_DS1 = []
sizeMemoryCol_DS1 = []
subject_DS1 = []
formats_DS1 = []



readDataSetWithSubjects(dir1, widthCol_DS1, heightCol_DS1, dirCol_DS1, sizeMemoryCol_DS1, subject_DS1, formats_DS1)

Construimos el dataframe con los arrays calculados y se obtiene un profile report

In [17]:
#Build dataframe
dataTable ={ 
    'Directory':  dirCol_DS1,
    'Subject': subject_DS1,    
    'Size': sizeMemoryCol_DS1,
    'Width': widthCol_DS1,
    'Height': heightCol_DS1,
    'format': formats_DS1
}
table = pd.DataFrame(dataTable, columns = ['Directory', 'Subject', 'Size', 'Width', 'Height', 'format'])
table

Directory             Subject  \
0      OriginalData/lfw-deepfunneled/Aaron_Eckhart/Aa...       Aaron_Eckhart   
1      OriginalData/lfw-deepfunneled/Aaron_Guiel/Aaro...         Aaron_Guiel   
2      OriginalData/lfw-deepfunneled/Aaron_Patterson/...     Aaron_Patterson   
3      OriginalData/lfw-deepfunneled/Aaron_Peirsol/Aa...       Aaron_Peirsol   
4      OriginalData/lfw-deepfunneled/Aaron_Peirsol/Aa...       Aaron_Peirsol   
...                                                  ...                 ...   
13228  OriginalData/lfw-deepfunneled/Zorica_Radovic/Z...      Zorica_Radovic   
13229  OriginalData/lfw-deepfunneled/Zulfiqar_Ahmed/Z...      Zulfiqar_Ahmed   
13230  OriginalData/lfw-deepfunneled/Zumrati_Juma/Zum...        Zumrati_Juma   
13231  OriginalData/lfw-deepfunneled/Zurab_Tsereteli/...     Zurab_Tsereteli   
13232  OriginalData/lfw-deepfunneled/Zydrunas_Ilgausk...  Zydrunas_Ilgauskas   

        Size  Width  Height format  
0       6855    250     250    jpg  
1       9631    250     250    jpg  
2       7556    250     250    jpg  
3       7877    250     250    jpg  
4       9700    250     250    jpg  
...      ...    ...     ...    ...  
13228  10095    250     250    jpg  
13229   8771    250     250    jpg  
13230   7250    250     250    jpg  
13231   8350    250     250    jpg  
13232   6977    250     250    jpg  

[13233 rows x 6 columns]

In [18]:
ProfileReport(table)

C:\Users\julia\Anaconda3\lib\site-packages\pandas_profiling\describe.py:392: FutureWarning:

The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.



#### Insights sobre data set #1

- En total hay 13233 imágenes que pertenecen a 5648 individuos distintos
- El formato, el ancho, y altura de las imagenes se mantiene constante (jpg, 250px y 250px respectivamente)
- La media del tamaño de las imágenes en la dataset es de 8810
- El individuo con más imágenes es George Bush con 530 fotos

### 3.2 Perfilamiento fuentes de datos #2

Esta fuente consiste en 2 carpetas de imagenes, en la primera se encuentran únicamente fotos de personas usando tapabocas (sin diferenciar si está bien o mal puesto) y en la segunda carpeta se encuentran fotos de personas sin usar tapabocas. 

Cabe destacar que el el objetivo de esta data set originalmente se enfocaba en face recognition, por lo cual dentro de cada carpeta hay subcarpetas que representan a una persona, y dentro de dicha se encuentran las fotos del sujeto

In [41]:
# Función que permite leer la data set descrita anteriormente dadas las columnas para guardar la información relevante
# y el directorio donde se encuentra
def readDataSetWithSubjectsDataSet2(directory, widthColumn, heightColumn, dirColumn, sizeMemoryColumn, subjectColumn, formatColumn, labels):
    
    #Iterate over both directories
    dirs = os.listdir(directory)
    
    # First directory is the one with out face masks
    maskDirectory = False
    for subdirectory in dirs:
        
        #Cur dir
        curDir = directory + subdirectory
        
        # Iterate over the directories in the data set
        files = os.listdir(curDir)
        for f in files:

            # Directory from each person
            dirPerson = curDir + '/' + f

            #Iterate over the images of each person
            for i in os.listdir(dirPerson):
                #Dir of an image of the person
                dirImg = dirPerson + '/' + i

                #Get width, height, size
                img = Image.open(dirImg)
                width, height = img.size
                size = os.stat(dirImg).st_size

                # Get the format
                formatOfImg = dirImg.split(".")[-1]
                
                # Get label
                label = "with_face_mask"
                if not maskDirectory:
                    label = "not_face_mask"

                #Append the data to the arrays
                widthColumn.append(width)
                heightColumn.append(height)
                sizeMemoryColumn.append(size)
                dirColumn.append(dirImg)
                subjectColumn.append(f)
                formatColumn.append(formatOfImg)
                labels.append(label)
        
        # Entering second directory (face masks)
        maskDirectory = True

In [42]:
# We obtain width, height, directory, size in bytes and subject
widthCol_DS2 = []
heightCol_DS2 = []
dirCol_DS2 = []
sizeMemoryCol_DS2 = []
subject_DS2 = []
formats_DS2 = []
labels_DS2 = []



readDataSetWithSubjectsDataSet2(dir2, widthCol_DS2, heightCol_DS2, dirCol_DS2, sizeMemoryCol_DS2, subject_DS2, formats_DS2, labels_DS2)

Construimos el dataframe con los arrays calculados y se obtiene un profile report

In [43]:
#Build dataframe
dataTable2 ={ 
    'Directory':  dirCol_DS2,
    'Subject': subject_DS2,    
    'Size': sizeMemoryCol_DS2,
    'Width': widthCol_DS2,
    'Height': heightCol_DS2,
    'format': formats_DS2,
    'label': labels_DS2
}
table2 = pd.DataFrame(dataTable2, columns = ['Directory', 'Subject', 'Size', 'Width', 'Height', 'format', 'label'])
table2

Directory      Subject   Size  \
0      OriginalData/self-built-masked-face-recognitio...        aidai   6318   
1      OriginalData/self-built-masked-face-recognitio...        aidai   7615   
2      OriginalData/self-built-masked-face-recognitio...        aidai   8266   
3      OriginalData/self-built-masked-face-recognitio...        aidai   5868   
4      OriginalData/self-built-masked-face-recognitio...        aidai   8791   
...                                                  ...          ...    ...   
92666  OriginalData/self-built-masked-face-recognitio...  zhuyuanbing  12360   
92667  OriginalData/self-built-masked-face-recognitio...   zoushiming   3835   
92668  OriginalData/self-built-masked-face-recognitio...   zoushiming   2511   
92669  OriginalData/self-built-masked-face-recognitio...   zoushiming   1085   
92670  OriginalData/self-built-masked-face-recognitio...    zuojinzhu  27604   

       Width  Height format           label  
0        140     147    jpg   not_face_mask  
1        152     135    jpg   not_face_mask  
2        146     127    jpg   not_face_mask  
3        148     121    jpg   not_face_mask  
4        146     131    jpg   not_face_mask  
...      ...     ...    ...             ...  
92666     67      90    png  with_face_mask  
92667     70      77    jpg  with_face_mask  
92668     43      52    jpg  with_face_mask  
92669     19      20    jpg  with_face_mask  
92670    254     251    jpg  with_face_mask  

[92671 rows x 7 columns]

In [44]:
ProfileReport(table2)

C:\Users\julia\Anaconda3\lib\site-packages\pandas_profiling\describe.py:392: FutureWarning:

The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.



#### Insights sobre data set #2

- En total hay 92671 imágenes que pertenecen a 538 individuos distintos
- El formato de la mayoria de imagenes es jpg. Una mínoría son png y jpeg (65 y 17 respectivamente)
- La media del tamaño de las imágenes en la dataset es de 6775 bits
- El individuo con más imágenes es liuyifei con 338 fotos
- Hay 90468 imágenes de personas sin tapabocas y 2203 con tapabocas

### 3.3 Perfilamiento fuente de datos #3

Esta fuente de datos contiene 853 fotos, cada una tiene un .xml asociado indicando características significantes de la imagen (largo, ancho, etc) y a su véz contiene la lista de caras que están en la imagen, cada una con los bounding box que la encierran y uno de los 3 siguientes labels: 'with_mask', 'without_mask', y 'mask_weared_incorrect'

1. Primero leemos solo una annotation para entender su estructura.

In [45]:
tree = ET.parse('OriginalData/kaggle_andrewmvd/annotations/maksssksksss0.xml')
root = tree.getroot()
# Nivel 1
print('Atributos nivel 1:')
for child in root:
    print (' - ' + child.tag)
    
print('\nAtributos del objeto que representa las caras:')
for child in root[4]:
    print (' - ' + child.tag)
    
print('\nAtributos del objeto que limita la cara:')
for child in root[4][-1] :
    print (' - ' + child.tag)

Atributos nivel 1:
 - folder
 - filename
 - size
 - segmented
 - object
 - object
 - object

Atributos del objeto que representa las caras:
 - name
 - pose
 - truncated
 - occluded
 - difficult
 - bndbox

Atributos del objeto que limita la cara:
 - xmin
 - ymin
 - xmax
 - ymax


- La lista de caras empieza desde el index 4 del root de cada xml.

- El label de las caras se encuentra en la pos 0 del objecto cara

- La bounding box está en la pos 5, y contiene 4 valores (pixeles que limitan la cara)

In [41]:
# Función que permite leer la data set descrita anteriormente dadas las columnas para guardar la información relevante
# y el directorio donde se encuentra
def readDataSetWithSubjectsDataSet2(directory, widthColumn, heightColumn, dirColumn, sizeMemoryColumn, imgColumn, formatColumn, labels):
    
    #Iterate over both directories
    dirs = os.listdir(directory)
    
    # First directory is the one with out face masks
    maskDirectory = False
    for subdirectory in dirs:
        
        #Cur dir
        curDir = directory + subdirectory
        
        # Iterate over the directories in the data set
        files = os.listdir(curDir)
        for f in files:

            # Directory from each person
            dirPerson = curDir + '/' + f

            #Dir of an image
            dirImg = dirPerson + '/' + f

            #Get width, height, size
            img = Image.open(dirImg)
            width, height = img.size
            size = os.stat(dirImg).st_size

            # Get the format
            formatOfImg = dirImg.split(".")[-1]

            # Get label
            label = "with_face_mask"
            if not maskDirectory:
                label = "not_face_mask"

            #Append the data to the arrays
            widthColumn.append(width)
            heightColumn.append(height)
            sizeMemoryColumn.append(size)
            dirColumn.append(dirImg)
            subjectColumn.append(f)
            formatColumn.append(formatOfImg)
            labels.append(label)
                    
        
        # Entering second directory (face masks)
        maskDirectory = True

In [47]:
# We obtain width, height, directory, size in bytes and # of subjects
widthCol_DS3 = []
heightCol_DS3 = []
dirCol_DS3 = []
sizeMemoryCol_DS3 = []
numSubjects_DS3 = []
labels_DS3 = [[],[],[]]
readDataSet3(dir3_annotations, dir3_images, widthCol_DS3, heightCol_DS3, dirCol_DS3, sizeMemoryCol_DS3, numSubjects_DS3, labels_DS3)

In [50]:
#Build dataframe
withM = labels_DS3[0]
dataTable3 ={ 
    'Directory':  dirCol_DS3,
    '# Subjects': numSubjects_DS3,    
    'Size': sizeMemoryCol_DS3,
    'Width': widthCol_DS3,
    'Height': heightCol_DS3,
    '# With mask': labels_DS3[0],
    '# no mask': labels_DS3[1],
    '# mask incorrectly': labels_DS3[2]
}
table3 = pd.DataFrame(dataTable3, columns = ['Directory', '# Subjects', 'Size', 'Width', 'Height','# With mask', '# no mask', '# mask incorrectly'])
table3

Directory  # Subjects    Size  \
0    OriginalData/kaggle_andrewmvd/images/maksssksk...           3  329899   
1    OriginalData/kaggle_andrewmvd/images/maksssksk...           9  351090   
2    OriginalData/kaggle_andrewmvd/images/maksssksk...           1  181960   
3    OriginalData/kaggle_andrewmvd/images/maksssksk...           3  543200   
4    OriginalData/kaggle_andrewmvd/images/maksssksk...           1  274025   
..                                                 ...         ...     ...   
848  OriginalData/kaggle_andrewmvd/images/maksssksk...           1  260929   
849  OriginalData/kaggle_andrewmvd/images/maksssksk...           4  494047   
850  OriginalData/kaggle_andrewmvd/images/maksssksk...           1  654037   
851  OriginalData/kaggle_andrewmvd/images/maksssksk...           4  641603   
852  OriginalData/kaggle_andrewmvd/images/maksssksk...           3  600123   

     Width  Height  # With mask  # no mask  # mask incorrectly  
0      512     366            1          2                   0  
1      400     156            8          1                   0  
2      301     400            1          0                   0  
3      400     226            3          0                   0  
4      301     400            1          0                   0  
..     ...     ...          ...        ...                 ...  
848    301     400            0          1                   0  
849    400     280            2          2                   0  
850    301     400            1          0                   0  
851    400     267            4          0                   0  
852    400     267            2          0                   1  

[853 rows x 8 columns]

In [51]:
ProfileReport(table3)

C:\Users\julia\Anaconda3\lib\site-packages\pandas_profiling\describe.py:392: FutureWarning:

The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.



Se obtiene el número de caras por cada label

In [52]:
print('Numero de personas con tapabocas bien puesto: ', table3['# With mask'].sum())
print('Numero de personas sin tapabocas: ', table3['# no mask'].sum())
print('Numero de personas con tapabocas mal puesto: ', table3['# mask incorrectly'].sum())
print('Total de caras: ', table3['# With mask'].sum() + table3['# no mask'].sum() + table3['# mask incorrectly'].sum())

Numero de personas con tapabocas bien puesto:  3232
Numero de personas sin tapabocas:  717
Numero de personas con tapabocas mal puesto:  123
Total de caras:  4072


#### Insights fuente de datos #3
- Se tiene un total de 	853 imágenes con 4072 caras de personas y un promedio de tamaño de 	488060 bytes.
- En esta fuente de datos, las clases están muy desbalanceadas, en particular la clase con tapabocas mal puesto solo tiene 123 caras

### 3.4 Perfilamiento fuente de datos #4

La estructura de esta dataset es similar a la #2, a diferencia que no hay sivision por subfolders con cada sujeto. Adicionalmente cabe resaltar que las imagenes del dataset han pasado por un proseso de augmentación.

In [79]:
# Función que permite leer la data set descrita anteriormente dadas las columnas para guardar la información relevante
# y el directorio donde se encuentra
def readDataSet4(directory, widthColumn, heightColumn, dirColumn, sizeMemoryColumn, originColumn, formatColumn, labels):
    
    maskDirectory = True
    # Iterate over the directories in the data set
    files = os.listdir(directory)
    for f in files:
        # Directory from each person
        dirPerson = directory + "/" + f

        #Iterate over the images of each person
        for i in os.listdir(dirPerson):
            
            #Dir of an image
            dirImg = dirPerson + '/' + i
            
             # Original img
            originalImg = i
            if "Augmented" in i:
                originalImg = i.split("_")[1]
        
            #Get width, height, size
            img = Image.open(dirImg)
            width, height = img.size
            size = os.stat(dirImg).st_size
            
            # Get the format
            formatOfImg = dirImg.split(".")[-1]
            
            # Get label
            label = "with_face_mask"
            if not maskDirectory:
                label = "not_face_mask"
        
            #Append the data to the arrays
            widthColumn.append(width)
            heightColumn.append(height)
            sizeMemoryColumn.append(size)
            dirColumn.append(dirImg)
            originColumn.append(originalImg)
            formatColumn.append(formatOfImg)
            labels.append(label)
        maskDirectory = False
            
 

In [80]:
# We obtain width, height, directory, size in bytes and subject
widthCol_DS4 = []
heightCol_DS4 = []
dirCol_DS4 = []
sizeMemoryCol_DS4 = []
originImg_DS4 = []
formats_DS4 = []
labels_DS4 = []



readDataSet4(dir4, widthCol_DS4, heightCol_DS4, dirCol_DS4, sizeMemoryCol_DS4, originImg_DS4, formats_DS4, labels_DS4)

Construimos el dataframe con los arrays calculados y se obtiene un profile report

In [81]:
#Build dataframe
dataTable4 ={ 
    'Directory':  dirCol_DS4,
    'OriginImg': originImg_DS4,    
    'Size': sizeMemoryCol_DS4,
    'Width': widthCol_DS4,
    'Height': heightCol_DS4,
    'format': formats_DS4,
    'label': labels_DS4
}
table4 = pd.DataFrame(dataTable4, columns = ['Directory', 'OriginImg', 'Size', 'Width', 'Height', 'format', 'label'])
table4

Directory OriginImg   Size  \
0      OriginalData/Ashish Jangra Face Mask Dataset/F...    10.png  16533   
1      OriginalData/Ashish Jangra Face Mask Dataset/F...   100.png   1786   
2      OriginalData/Ashish Jangra Face Mask Dataset/F...  1002.png  20625   
3      OriginalData/Ashish Jangra Face Mask Dataset/F...  1003.png  25754   
4      OriginalData/Ashish Jangra Face Mask Dataset/F...  1004.png   5772   
...                                                  ...       ...    ...   
11787  OriginalData/Ashish Jangra Face Mask Dataset/n...   995.png  22967   
11788  OriginalData/Ashish Jangra Face Mask Dataset/n...   996.png  20505   
11789  OriginalData/Ashish Jangra Face Mask Dataset/n...   997.png  23998   
11790  OriginalData/Ashish Jangra Face Mask Dataset/n...   998.png  22809   
11791  OriginalData/Ashish Jangra Face Mask Dataset/n...   999.png  20548   

       Width  Height format           label  
0         82      82    png  with_face_mask  
1         25      25    png  with_face_mask  
2        100     100    png  with_face_mask  
3        118     118    png  with_face_mask  
4         50      50    png  with_face_mask  
...      ...     ...    ...             ...  
11787    100     100    png   not_face_mask  
11788    100     100    png   not_face_mask  
11789    106     106    png   not_face_mask  
11790    103     103    png   not_face_mask  
11791    101     101    png   not_face_mask  

[11792 rows x 7 columns]

In [82]:
ProfileReport(table4)

C:\Users\julia\Anaconda3\lib\site-packages\pandas_profiling\describe.py:392: FutureWarning:

The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.



#### Insights sobre data set #4

- En total hay 11792 imágenes (Sin augmentación son 6818), 5909 sin uso de tapabocas y 5883 con uso de tapabocas
- El formato de todas las imágenes es png, la altura y ancho tienen correlación de (ρ = 1) con valor de 142 pixeles
- La media del tamaño de las imágenes en la dataset es de 9947 bits
- Al ver las imágenes se puede evidenciar que hay imágenes que no corresponden a personas reales (dibujos de caras) y también algunas imágenes con label incorrecto.

## 4 Limpieza de datos:
- No se hace limpieza sobre las imágenes ya que en ambas fuentes de datos tenían un trabajo previo para que las imágenes fueran usadas en contextos de machine learning. 

## 5. Procesamiento

### 2.1 Simulación de tapabocas con face recognition (Con fuentes de datos 1 y 2)

Para evitar overfitting y posible bias en el algoritmo de aprendizaje, se trabaja con una imagen por persona y se obtiene el siguiente esquema de imagenes:

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0lax">Clase</th>
    <th class="tg-0lax"># Imágenes</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0lax">Sin tapabococas</td>
    <td class="tg-0lax">2069</td>
  </tr>
  <tr>
    <td class="tg-0lax">Tapabocas usado correctamente</td>
    <td class="tg-0lax">2070</td>
  </tr>
  <tr>
    <td class="tg-0lax">Tapabocas usado incorrectamente</td>
    <td class="tg-0lax">2070</td>
  </tr>
</tbody>
</table>

La primera parte del procesamiento consite en simular el uso de máscaras (correcta e incorrectamente) utilizando el paquete 'face_recognition' y las siguientes imágenes de tapabocas en formato .png :

<img src="https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/Masks/sampleForNotebook.jpg?raw=true" ><br>
- Cada tipo de tapabocas será usado 2070/5 veces para cada una de las clases tapabocas usado correctamente y tapabocas usado incorrectamente.

La simulación de imágenes con uso de tapabocas incorrecto se basará en la imagen publicada por la revista Vale indicando los errores más comunes al momento de usar tapabocas:
<img src="http://www.vale.com/brasil/pt/aboutvale/news/publishingimages/news/2020/maio/mascara/header-mas-desk.png" ><br>
Obtenido de: http://www.vale.com/EN/aboutvale/news/Pages/How-to-Wear-a-Face-Mask-Correctly-and-Common-Mistakes-to-Avoid-.aspx

Para procesar las imágenes y simular el uso de tapabocas, se realiza un archivo .py que usa el paquete 'face_recognition' y obteniendo los puntos clave de la cara (naríz y mentón) se hace el siguiente procedimiento por cada foto:

1) Se indica el path de la imagen con la cara, path de la máscara a sobreponer, el path en donde debe ser guardada la imagen a ser construída y si la máscara debe ser puesta correctamente o incorrectamente. 

2) Detectar si en la foto se encuentra la cara de una persona usando el paquete face_recognition, si no se encuentra ninguna cara se detiene la ejecución para esa foto.

3) Si hay una cara de una persona, por medio del paquete face_recognition se obtienen los pixeles donde se encuentra la punta de la nariz, los extremos del mentón y la punta del mentón. Con estos puntos se calcula cómo debe rotarse la máscara al momento de sobreponerla.

4) Con los puntos anteriores se utiliza PIL para poner la máscara indicada (en formato .png) sobre la cara de la persona. Si se indica que la máscara debe ser puesta 'incorrectamente' se sobrepone por debajo de la nariz, de lo contrario desde arriba de la punta de la nariz hasta la punta del mentón

* El código utilizado para poner las máscaras fue principalmente obtenido del siguiente repositorio: https://github.com/prajnasb/observations, donde se modificó y añadió lo siguiente:
 - Iterar sobre los datos mostrados en perfilamiento
 - Funcionalidad de poner la máscara 'usada incorrectamente'
 - Funcionalidad para poner cualquier máscara dada por parámetro


* La ejecución de este proceso se hace en un .py ya que no fue posible instalar el packete 'face_recognition' en el ambiente de python de anaconda

El .py se encuentra en el siguiente repositorio: https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/MaskPlacer.py

### 2.2 Resultados de la simulación

Algunos resultados de simulación de tapabocas puestos correctamente:
<img src="https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/Masks/sampleMasking0.jpg?raw=true" ><br>

Algunos resultados de tapabocas puestos incorrectamente:
<img src="https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/Masks/sampleMasking1.jpg?raw=true" ><br>

### 2.3 Limpieza manual sobre los resultados de la simulación
- Se miran todas las imágenes simuladas manualmente y se eliminan las que por variadas razones como expresiones de las personas, objetos cruzados, tamaño de la cara en pixeles al sobreponerse el tapabocas no daban resultado esperado.

Los estandáres para decidir cuando eliminar fueron:
- Tiras demasiado alejadas de las orejas
- Tapabocas sobrepuesto demasiado debajo de la nariz
- Tapabocas en la punta de la nariz o por debajo (en clase de uso correcto)

In [9]:
# Getting number of files in each dir
dirMaskPoorly = 'ProcessedData/MaskPoorlyPlaced'

files = os.listdir(dirMaskPoorly)
print('Total images where mask is used poorly: ' +  str(len(files)))

dirMask = 'ProcessedData/MaskWellPlaced'

files = os.listdir(dirMask)
print('Total images where mask is used properly: ' +  str(len(files)))

dirNoMask = 'ProcessedData/NoMask'

files = os.listdir(dirNoMask)
print('Total images where there is no use of mask: ' +  str(len(files)))

Total images where mask is used poorly: 1978
Total images where mask is used properly: 1320
Total images where there is no use of mask: 2069


### 2.4 Separar caras según label en fuente de datos 3 (Añadido revisión 1)

In [130]:
tree = ET.parse('OriginalData/kaggle_andrewmvd/annotations/maksssksksss0.xml')
root = tree.getroot()
img = Image.open('OriginalData/kaggle_andrewmvd/images/maksssksksss0.png')
area = (int(root[5][-1][0].text) , int(root[5][-1][1].text), int(root[5][-1][2].text), int(root[5][-1][3].text))
imgCrop = img.crop(area)
imgCrop.save('nuevo.png')

In [3]:
directoryAnnotations = 'OriginalData/kaggle_andrewmvd/annotations/'
files = os.listdir(directoryAnnotations)
for f in files:
        
    # Read .xml
    tree = ET.parse(directoryAnnotations + f)
    root = tree.getroot()
        
     # Get photo name
    imgName = root[1].text
            
    #Directory from each foto
    dirPhoto = 'OriginalData/kaggle_andrewmvd/images/' + imgName
        
    #Get width, height, size
    img = Image.open(dirPhoto)
    
    # Split name with ext
    imgName = imgName.split('.')
        
    # Get labels
    for i in range(4, len(root)):
        # Get label
        label = root[i][0].text 
        
        # Get dir to place the cropped img
        labelDir = ''
        if label == 'with_mask':
            labelDir = 'MaskWellPlaced/'
        elif label == 'without_mask':
            labelDir = 'NoMask/'
        else:
            labelDir = 'MaskPoorlyPlaced/'
        
        # Get the area
        area = (int(root[i][-1][0].text) , int(root[i][-1][1].text), int(root[i][-1][2].text), int(root[i][-1][3].text))
        
        # Only crop when he image is bigger than 100*100
        if area[2] - area[0] >= 50 and area[3] - area[1] >= 50: 
            # Crop the image
            imgCrop = img.crop(area)
            imgCrop.save('OriginalData/kaggle_andrewmvd/croppedImages/' + labelDir + imgName[0] + '_subject_' + str(i-3)  + '.' + imgName[1])

### 2.4 Separar train y test
Se construye un dataframe con directorios y clase, luego se crea un .csv con esos datos

In [137]:
directories = []
classCol = []

#Iterate over processed data
dir = 'ProcessedData/'
files = os.listdir(dir)
for i in files:
    clase = i
    if not clase == 'data.csv' and not clase == 'splitedProcessedData': 
        for j in os.listdir(dir + i):
            directories.append(dir + i + '/' + j)
            classCol.append(clase)

# Iterate over the cropped images from data set #3
dir = 'OriginalData/kaggle_andrewmvd/imagesCropped/'
files = os.listdir(dir)
for i in files:
    clase = i
    for j in os.listdir(dir + i):
        directories.append(dir + i + '/' + j)
        classCol.append(clase)   
            
#Build dataframe
dataTable ={ 
    'Directory':  directories,
    'Class': classCol,    
}
table = pd.DataFrame(dataTable, columns = ['Directory', 'Class'])
table        

Directory             Class
0     ProcessedData/MaskPoorlyPlaced/Aaron_Eckhart_0...  MaskPoorlyPlaced
1     ProcessedData/MaskPoorlyPlaced/Aaron_Peirsol_0...  MaskPoorlyPlaced
2     ProcessedData/MaskPoorlyPlaced/Aaron_Tippin_00...  MaskPoorlyPlaced
3     ProcessedData/MaskPoorlyPlaced/Abdel_Madi_Shab...  MaskPoorlyPlaced
4     ProcessedData/MaskPoorlyPlaced/Abdoulaye_Wade_...  MaskPoorlyPlaced
...                                                 ...               ...
9939  OriginalData/kaggle_andrewmvd/imagesCropped/No...            NoMask
9940  OriginalData/kaggle_andrewmvd/imagesCropped/No...            NoMask
9941  OriginalData/kaggle_andrewmvd/imagesCropped/No...            NoMask
9942  OriginalData/kaggle_andrewmvd/imagesCropped/No...            NoMask
9943  OriginalData/kaggle_andrewmvd/imagesCropped/No...            NoMask

[9944 rows x 2 columns]

Escribe el df en el .csv dado

In [139]:
table.to_csv(input('Escribir en: '),index=False)

Escribir en: C:/Users/julia/OneDrive/Documents/uniLocal/MLT/Proyect/Face-mask-detector-with-machine-learning/DataProcessor/ProcessedData/data.csv


Partir splits de entrenamiento y training

In [140]:
X_train, X_test, y_train, y_test = train_test_split(table['Directory'] , table['Class'] , test_size=0.2, random_state=33)

Copiar imagenes en carpetas según training y test

In [141]:
def copyImages(vectorX, y, targetDirectory):
    aux = 0
    for filePath, clase in zip(vectorX, y):
        copyfile(filePath, targetDirectory + '/' + clase + '/' + filePath.split('/')[-1])

In [148]:
copyImages(X_train,y_train, input('Target train: '))

Target train: C:/Users/julia/OneDrive/Documents/uniLocal/MLT/Proyect/Face-mask-detector-with-machine-learning/DataProcessor/ProcessedData/splitedProcessedData/train


In [149]:
copyImages(X_test,y_test, input('Target test: '))

Target test: C:/Users/julia/OneDrive/Documents/uniLocal/MLT/Proyect/Face-mask-detector-with-machine-learning/dataProcessor/ProcessedData/splitedProcessedData/test


Resultados de las anteriores lineas:
Una carpeta para test, otra para training
<img src="https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/Masks/notebook0.jpg?raw=true" ><br>
En test y training 3 carpetas (1 por clase)
<img src="https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/Masks/notebook1.jpg?raw=true" ><br>
Las imagenes según las clase
<img src="https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/Masks/notebook2.jpg?raw=true" ><br>
<img src="https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/Masks/notebook3.jpg?raw=true" ><br>
<img src="https://github.com/jcmontoyar/Face-mask-detector-with-machine-learning/blob/master/DataProcessor/Masks/notebook4.jpg?raw=true" ><br>